<!DOCTYPE html>
<html>

<head>
    <meta name="theme-color" content="#1B6E74">
    <meta charset="utf-8" />
    <title>Gerenciador Gourmeet</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/css/style.css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
</head>

<body id="LoginForm">
    <div class="container">
        <h1 class="form-heading pt-5 pb-5">Seja bem vindo</h1>
        <div class="login-form">
            <div class="main-div">
                <div class="panel">
                    <h2>Cadastro de Produtos</h2>
                    <p>Por favor, cadastre seus produtos</p>
                </div>
                <form method="post" action="/produtoCadastroNoBanco/" id="Update">

                    <div class="form-group">





                        <input type='text' required class='form-control' name='nomeProduto' id='produtoInput' placeholder='Nome do produto'></input>
                        <div class='mt-3'></div>
                        <textarea class='form-control' required name="descProduto" id='exampleFormControlTextarea1' rows='1' placeholder='Descrição do produto'></textarea>
                        <div class='mt-3'></div>
                        <input type='number' step='any' required min='2' max='3000' class='form-control' name='precoProduto' id='produtoInput' placeholder='Preço'></input>
                        <div class='mt-3'></div>
                        <select class="form-control" id="exampleFormControlSelect1" name="idCategoria">
                            <?php
                            foreach ($mostrarCategoria as $key => $value) {
                                echo "<option value='" . $value['idCategoria'] . "'>" . $value['nomeCategoria'] . "</option>";
                            }
                            ?>
                        </select>
                        <div class='mt-3'></div>


















                        
                        <select required class="form-control" id="exampleFormControlSelect1" name="ehDestaque">
                            <option value="0" selected>Transformar em destaque?</option>

                            <option value="1">Sim</option>

                            <option value="0">Não</option>

                        </select>




                    </div>
                    <div class="forgot">

                    </div>
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                </form>
                <hr>
                <a href="/produtos/"><button class="btn btn-primary">Voltar</button></a>


            </div>
        </div>
    </div>


</body>

</html>