<!DOCTYPE html>
<html>

<head>
    <meta name="theme-color" content="#1B6E74">
    <meta charset="utf-8" />
    <title>Gerenciador Gourmeet</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/css/style.css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
</head>

<body id="LoginForm">
    <div class="container">
        <h1 class="form-heading pt-5 pb-5">Seja bem vindo</h1>
        <div class="login-form">
            <div class="main-div">
                <div class="panel">
                    <h2>Cadastro de categoria</h2>
                    <p>Por favor, cadastre a nova categoria</p>
                </div>
                <form method="post" action="/categoriaCadastroNoBanco/" id="Login">

                    <div class="form-group">


                        <input required type="text" class="form-control" name="categoria" id="categoriaInput" placeholder="Adicionar categoria">

                    </div>
                    <div class="forgot">

                    </div>
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                </form>
                <hr>
                <a href="/categorias/"><button class="btn btn-primary">Voltar</button></a>


            </div>
        </div>
    </div>


</body>

</html>