<!DOCTYPE html>
<html>

<head>
    <meta name="theme-color" content="#1B6E74">
    <meta charset="utf-8" />
    <title>Gerenciador Gourmeet</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/css/style.css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
</head>

<body id="LoginForm">
    <div class="container">
        <h1 class="form-heading pt-5 pb-5">Seja bem vindo</h1>
        <div class="login-form">
            <div class="main-div">
                <div class="panel">
                    <h2>Editor de Produtos</h2>
                    <p>Por favor, edite seus produtos</p>
                </div>
                <form method="post" action="/produtoEditado/" id="Update">

                    <div class="form-group">

                        <?
                        foreach ($produtoEditar as $key => $value) {
                            echo "<input type='hidden' name='idProduto' value='" . $value['idProduto'] . "'>"; 
                            echo "<input type='text' class='form-control' name='nome' id='produtoInput' value='" . $value['nomeProduto'] . "'>" . "</input>";
                            echo "<div class='mt-3'>" . "</div>";
                            echo "<textarea class='form-control' id='exampleFormControlTextarea1' name='descricao' rows='10' value='" . $value['descProduto'] . "'>" . "</textarea>";
                            echo "<div class='mt-3'>" . "</div>";
                            echo "<input type='number' step='any' min='0' max='100' class='form-control' name='preco' id='produtoInput' value='" . $value['precoProduto'] . "'>" . "</input>";
                        }
                        ?>

                    </div>
                    <div class="forgot">

                    </div>
                    <a href=""><button type="submit" class="btn btn-primary">Cadastrar</button></a>
                </form>
                <hr>
                <a href="/produtos/"><button class="btn btn-primary">Voltar</button></a>


            </div>
        </div>
    </div>


</body>

</html>