<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/css/style.css">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  </head>
<body id="LoginForm">
<div class="container">
<h1 class="form-heading pt-5 pb-5">Cadastro</h1>
<div class="login-form">
<div class="main-div">
    <div class="panel">
   <h2>Cadastro de admin Gourmeet</h2>
   <p>Cadastre os produtos de seu carápio aqui</p>
   </div>
    <form id="Login">

        <div class="form-group">


            <input type="text" class="form-control" id="inputnome" placeholder="Nome do produto">

        </div>

        <div class="form-group">

            <input type="text" class="form-control" id="inputPassword" placeholder="">

        </div>
        
        <div class="form-group">

            <input type="password" class="form-control" id="inputPassword" placeholder="Confirmar senha">

        </div>
        <div class="forgot">
     
</div>
        <a href=""><button type="submit" class="btn btn-primary">Login</button></a>
        <hr>
        <button type="submit" class="btn btn-primary">Cadastrar</button>

    </form>
    </div>

</div></div></div>


</body>
</html>