<!DOCTYPE html>
<html>

<head>
    <meta name="theme-color" content="#1B6E74"> 
    <meta charset="utf-8" />
    <title>Gerenciador Gourmeet</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/css/style.css">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
  </head>
<body id="LoginForm">
<div class="container">
<h1 class="form-heading pt-5 pb-5">Acesso Administração</h1>
<div class="login-form">
<div class="main-div">
    <div class="panel">
   <h2>Gerenciador de cardápios</h2>
   <p>Por favor, digite seu email e senha</p>
   </div>
    <form action="/login/" method="post" id="Login">

        <div class="form-group">


            <input type="email" class="form-control" name="email" id="inputEmail" placeholder="Endereço de email">

        </div>

        <div class="form-group">

            <input type="password" class="form-control" name="senha" id="inputPassword" placeholder="Senha">

        </div>  
        <div class="forgot">
     
</div>
        <button type="submit" class="btn btn-primary">Login</button>
        <hr>
        
    </form>
    <a href="/cadastro/"><button type="submit" class="btn btn-primary">Cadastrar</button></a>
    </div>

</div></div></div>


</body>
</html>
