<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Selecione a sua opção</title>
    <link rel="stylesheet" href="/css/style.css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>

<body>
    <div class="container-fluid">
        <div class="row">

            <a href="/gerenciador/"><div class="col-sm-12 col-md-12 col-lg-6 col-xl-6" id="gerenciadorSel">

                <div class="row">
                    <div class="col-12">
                        <h1 style="margin-top:40vh">
                            Gerenciador
                        </h1>
                    </div>
                </div>
                </a>
            </div>
           <a href="localhost:1234"> <div class="col-sm-12 col-md-12 col-lg-6 col-xl-6" id="cardapioSel">

            <div class="row">
                <div class="col-12">
                    <h1 style="margin-top:40vh">
                        Cardápio
                    </h1>
                </div>
            </div></a>



        </div>
    </div>
    </div>
</body>

</html>