<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <title>Gerenciador gourmeet</title>
  <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="/css/gerenteStyle.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" />


  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>



</head>

<body>


  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading">
        <h4>Opções</h4>
      </div>
      <div class="list-group list-group-flush">
      <a href="/login/" class="list-group-item list-group-item-action bg-light">Início</a>
        <a href="/categorias/" class="list-group-item list-group-item-action bg-light">Categorias</a>
        <a href="/produtos/" class="list-group-item list-group-item-action bg-light">Produtos</a>
        <a href="/pedidos/" class="list-group-item list-group-item-action bg-light">Pedidos</a>
        <a href="/pedidosPagos/" class="list-group-item list-group-item-action bg-light">Pedidos pagos</a>
        <a href="/clientes/" class="list-group-item list-group-item-action bg-light">Clientes</a>

        <a href="#" class="list-group-item list-group-item-action bg-light">Sair</a>

      </div>
    </div>

    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <a id="menu-toggle">
          <h4>Gourmeet<h4>
        </a>




        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
            </li>
          </ul>
        </div>
      </nav>

      <div class="container-fluid">
        <div class="row">
          <div class="col-11">
            <h1 class="mt-4 mb-4">Clientes atuais</h1>
          </div>
          <div class="col-1">
        
             
          </div>

        </div>




        <?php

        echo "<table class='table'>";
        echo "<thead>";
        echo "<tr>";
        echo  "<th scope='col'>Nome do cliente</th>";
        echo "<th scope='col'>Mesa</th>";
      
        echo  "<th scope='col'>Status mesa</th>";
        echo " </tr>";
        echo "</thead>";
        foreach ($pedidosClientes as $key => $value) {
          echo "<tbody>";
          echo "<tr>";

          echo "<td>";
          echo $value['nomeCliente'];
          echo "</td>";
          echo "<td>";
          echo $value['idMesa'];
          echo "</td>";
          if ($value['statusPagamento']==0) {
            echo "<td>";
            echo "<i class='fas fa-times'>"."</i>";
            echo "</td>";
           
          }else {
            # code...
            echo "<td>";
            echo "<i class='fas fa-check-circle'>"."</i>";
            echo "</td>";
          }

          echo "</tr>";
        }


        ?>
      </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>
</body>

</html>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

</html>